services:
  bruhbackend:
    container_name: bruh.chat.backend
    build:
      context: ./bruh-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin}
      - SECRET_KEY=${SECRET_KEY:-temp-secret-key-change-in-production}
    volumes:
      - db_data:/app/db
      - media_data:/app/media
    networks:
      - app-network

  bruhfrontend:
    container_name: bruh.chat.frontend
    build:
      context: ./bruh-frontend
      dockerfile: Dockerfile
      args:
        - VITE_APP_BACKEND_API_URL=${VITE_APP_BACKEND_API_URL:-http://localhost:8000}
        - VITE_APP_BACKEND_API_VERSION=${VITE_APP_BACKEND_API_VERSION:-api}
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - bruhbackend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  media_data: